# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZG8M_fbAfdkgOX3Rz-gELR-suTsClxn4
"""

import os, zipfile

dir_name = './'
extension = "zip"

os.chdir(dir_name) # change directory from working dir to dir with files
password='infected'
for item in os.listdir(dir_name):
  print(item)
  if item.endswith(extension):
    file_name = os.path.abspath(item)
    print(file_name)
    zip_ref = zipfile.ZipFile(file_name)
    zip_ref.extractall(dir_name, pwd=bytes(password,'utf-8'))
    zip_ref.close() # close file